version: 1.0.0.{build}

environment:
  matrix:
    - node_version: "7"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

branches:
  except:
  - design

image: Visual Studio 2017

install:
- ps: Install-Product node $env:node_version
- cmd: >-
    cd Anlab.Mvc
    
    yarn install

    cd ..

- cmd: dotnet restore
- cmd: echo %APPVEYOR_REPO_COMMIT_MESSAGE% > commit.txt 

cache:
- packages -> **\packages.config
- anlab.mvc\node_modules -> **\package.json

build_script:
- cmd: dotnet build -c Release

after_build:
- cmd: dotnet publish .\Anlab.Mvc\AnlabMvc.csproj --output %appveyor_build_folder%\dist

test_script:
- cmd: dotnet test .\Test\Test.csproj -l Appveyor
- cmd: >-
    cd Anlab.Mvc

    npm test

    cd ..

artifacts:
- path: '**/octopacked/Anlab.*.nupkg'
  name: nugetweb

deploy:
- provider: NuGet
  server: https://scruffy.caes.ucdavis.edu/nuget/packages
  api_key:
    secure: UBO7nAPSvgx5lKiqX0FTNi4HQatzLx+XgbYhfvGmzRU=
  skip_symbols: true
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: caes-development
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
